version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./documents:/app/documents
      - ./chromadb:/app/chromadb
    environment:
      - OLLAMA_HOST=http://localhost:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

volumes:
  ollama_data: 